In [1]:
import pandas as pd

In [10]:
df=pd.read_csv("Hospital_Appointment.csv",  encoding="latin1")
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,WaitingDays,Age Group
0,4.314930e+14,5640380,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,MONTE BELO,0,0,0,0,0,0,No,0,Under 18
1,6.822850e+13,5642813,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,BONFIM,0,0,0,0,0,0,No,0,Under 18
2,5.392419e+10,5641476,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,ITARARÃ,0,0,0,0,0,0,No,0,Under 18
3,1.883370e+14,5640933,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,NOVA PALESTINA,0,0,0,0,0,0,No,0,Under 18
4,1.165340e+12,5640561,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,CONQUISTA,0,0,0,0,0,0,No,0,Under 18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,5.342900e+12,5778205,F,"Monday, June 6, 2016","Monday, June 6, 2016",66,TABUAZEIRO,0,1,0,0,1,0,No,0,Over 60
110523,5.342900e+12,5778066,F,"Monday, June 6, 2016","Monday, June 6, 2016",66,TABUAZEIRO,0,1,0,0,1,0,No,0,Over 60
110524,8.588820e+12,5759465,F,"Wednesday, June 1, 2016","Wednesday, June 1, 2016",83,DO QUADRO,0,1,0,0,1,0,No,0,Over 60
110525,4.758510e+13,5784948,F,"Tuesday, June 7, 2016","Tuesday, June 7, 2016",96,SANTO ANTÃNIO,0,1,0,0,1,0,No,0,Over 60
110526,3.184920e+13,5756880,F,"Wednesday, June 1, 2016","Wednesday, June 1, 2016",81,ITARARÃ,0,1,0,0,1,0,No,0,Over 60

In [12]:
print(df.head())
print(df.info())
print(df.isnull().sum())
print(df.duplicated().sum())

      PatientId  AppointmentID Gender            ScheduledDay  \
0  4.314930e+14        5640380      M  Friday, April 29, 2016
1  6.822850e+13        5642813      M  Friday, April 29, 2016
2  5.392419e+10        5641476      M  Friday, April 29, 2016
3  1.883370e+14        5640933      M  Friday, April 29, 2016
4  1.165340e+12        5640561      M  Friday, April 29, 2016

           AppointmentDay  Age   Neighbourhood  Scholarship  Hipertension  \
0  Friday, April 29, 2016    0      MONTE BELO            0             0
1  Friday, April 29, 2016    0          BONFIM            0             0
2  Friday, April 29, 2016    0        ITARARÃ            0             0
3  Friday, April 29, 2016    0  NOVA PALESTINA            0             0
4  Friday, April 29, 2016    0       CONQUISTA            0             0

   Diabetes  Alcoholism  Handcap  SMS_received No-show  WaitingDays Age Group
0         0           0        0             0      No            0  Under 18
1         0           0        0             0      No            0  Under 18
2         0           0        0             0      No            0  Under 18
3         0           0        0             0      No            0  Under 18
4         0           0        0             0      No            0  Under 18
<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  str
 3   ScheduledDay    110527 non-null  str
 4   AppointmentDay  110527 non-null  str
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  str
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  str
 14  WaitingDays     110527 non-null  int64
 15  Age Group       110527 non-null  str
dtypes: float64(1), int64(9), str(6)
memory usage: 13.5 MB
None
PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
WaitingDays       0
Age Group         0
dtype: int64
0

In [30]:
df.rename(columns= {"Hipertension":"Hypertension"},inplace=True)
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,WaitingDays,Age Group
0,4.314930e+14,5640380,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,MONTE BELO,0,0,0,0,0,0,No,0,Under 18
1,6.822850e+13,5642813,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,BONFIM,0,0,0,0,0,0,No,0,Under 18
2,5.392419e+10,5641476,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,ITARARÃ,0,0,0,0,0,0,No,0,Under 18
3,1.883370e+14,5640933,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,NOVA PALESTINA,0,0,0,0,0,0,No,0,Under 18
4,1.165340e+12,5640561,M,"Friday, April 29, 2016","Friday, April 29, 2016",0,CONQUISTA,0,0,0,0,0,0,No,0,Under 18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,5.342900e+12,5778205,F,"Monday, June 6, 2016","Monday, June 6, 2016",66,TABUAZEIRO,0,1,0,0,1,0,No,0,Over 60
110523,5.342900e+12,5778066,F,"Monday, June 6, 2016","Monday, June 6, 2016",66,TABUAZEIRO,0,1,0,0,1,0,No,0,Over 60
110524,8.588820e+12,5759465,F,"Wednesday, June 1, 2016","Wednesday, June 1, 2016",83,DO QUADRO,0,1,0,0,1,0,No,0,Over 60
110525,4.758510e+13,5784948,F,"Tuesday, June 7, 2016","Tuesday, June 7, 2016",96,SANTO ANTÃNIO,0,1,0,0,1,0,No,0,Over 60
110526,3.184920e+13,5756880,F,"Wednesday, June 1, 2016","Wednesday, June 1, 2016",81,ITARARÃ,0,1,0,0,1,0,No,0,Over 60

In [13]:
df["No-show"].value_counts()

No-show
No     88208
Yes    22319
Name: count, dtype: int64

In [40]:
df.groupby("Gender")["No-show"].value_counts()

Gender  No-show
F       No         57246
        Yes        14594
M       No         30962
        Yes         7725
Name: count, dtype: int64

In [35]:
df.groupby("Age Group") [["Diabetes","Hypertension"]].agg(["sum","count"])

          Diabetes        Hypertension
               sum  count          sum  count
Age Group
18 - 30        117  18252          326  18252
31 - 45        784  21954         2661  21954
46 - 60       2604  23179         7774  23179
Over 60       4387  19762        11002  19762
Under 18        51  27380           38  27380

In [38]:
df["SMS_received"].value_counts()

SMS_received
0    75045
1    35482
Name: count, dtype: int64